services:
  psql:
    image: postgres:17.2
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=ViewerDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 5s
      retries: 3
  
  server:
    build:
      context: .
      dockerfile: src/server/Viewer.Server.Presentation/Dockerfile
  
volumes:
  postgres_data:
    driver: local