services:
  database:
    image: "docker.io/library/postgres:17.4"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "8000:5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "viewer.server.aspire.apphost-60d5372ba1-database-data"
        read_only: false
    networks:
      - "aspire"
  viewer-server-presentation:
    image: "${VIEWER_SERVER_PRESENTATION_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8001;8081"
      ConnectionStrings__ViewerDb: "Host=database;Port=5432;Username=postgres;Password=${DATABASE_PASSWORD};Database=ViewerDb"
    ports:
      - "8002:8001"
      - "8004:8003"
      - "8080:8081"
    depends_on:
      database:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  viewer.server.aspire.apphost-60d5372ba1-database-data:
    driver: "local"
