apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: vitaliipriadilia/viewer-server:latest
          ports:
            - containerPort: 8080 # HTTP port
            - containerPort: 8081 # HTTPS port
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: "https://+:8081;http://+:8080"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: /https/https-cert.pfx
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              value: changeit
            - name: ConnectionStrings__DefaultConnection
              value: Host=db;Port=5432;Database=yourdb;Username=youruser;Password=password
          volumeMounts:
            - name: https-pfx-volume    
              mountPath: /https
              readOnly: true
      volumes:
        - name: https-pfx-volume
          secret:
            secretName: https-pfx-cert

