apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
      
    - name: https
      port: 8081
      targetPort: 8081
      nodePort: 30443
