---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  labels:
    app: aspire
    component: database
data:
  POSTGRES_HOST_AUTH_METHOD: "{{ .Values.config.database.POSTGRES_HOST_AUTH_METHOD }}"
  POSTGRES_INITDB_ARGS: "{{ .Values.config.database.POSTGRES_INITDB_ARGS }}"
  POSTGRES_USER: "{{ .Values.config.database.POSTGRES_USER }}"
