---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  type: ClusterIP
  selector:
    app: aspire
    component: database
  ports:
    - name: "tcp"
      protocol: "TCP"
      port: 5432
      targetPort: 5432
