---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: viewer-server-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: aspire
      component: viewer-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: aspire
        component: viewer-server
    spec:
      containers:
        - name: viewer-server
          image: {{ index .Values.parameters "viewer-server" "viewer_server_image" | quote }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: viewer-server-config
            - secretRef:
                name: viewer-server-secrets
          ports:
            - name: http
              protocol: TCP
              containerPort: {{ index .Values.parameters "viewer-server" "port_http" }}
            - name: https
              protocol: TCP
              containerPort: {{ index .Values.parameters "viewer-server" "port_https" }}
          volumeMounts:
            {{- range .Values.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
            {{- end }}
      volumes:
        {{- range .Values.volumes }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secret.secretName }}
        {{- end }}

